name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Nix cache
      uses: cachix/cachix-action@v12
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build binary
      run: nix build

    - name: Copy binary
      run: cp result/bin/zemon zemon-linux-x86_64

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: zemon-linux-x86_64
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get SHA256 checksum
      id: sha256
      run: echo "sha256=$(sha256sum zemon-linux-x86_64 | awk '{print $1}')" >> $GITHUB_OUTPUT

    - name: Update PKGBUILD
      run: |
        version=${GITHUB_REF_NAME#v}
        sed -i "s/^pkgver=.*/pkgver=$version/" PKGBUILD
        sed -i "s/^sha256sums=.*/sha256sums=('${{ steps.sha256.outputs.sha256 }}')/" PKGBUILD

    - name: Deploy to AUR
      uses: KSXGitHub/github-actions-deploy-aur@v2.6.0
      with:
        pkgname: ${{ env.AUR_PKGNAME }}
        commit_username: ${{ env.AUR_USERNAME }}
        commit_email: ${{ env.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
